### ISSUE TITLE
irc: not enough memory

### ISSUE THREAD

**Issue by kashike** [weechat/weechat#573]
I'm encountering the following issue:

```
08:28:10 =!= | irc: reading data on socket: error -54 Error in the pull function.
08:28:10  -- | irc: disconnecting from server...
08:28:10  -- | irc: disconnected from server
08:28:10  -- | irc: reconnecting to server in 10 seconds
08:28:20  -- | irc: reconnecting to server...
08:28:20  -- | irc: connecting to server ... (SSL)...
08:28:20 =!= | irc: not enough memory
```

on reconnect, the same thing (`irc: not enough memory`) happens. The only solution is to restart weechat. So far, from what I recall, it is only occurring on one network (rizon).

`OpenSSL 1.0.1f 6 Jan 2014`

```
10:59:08     | Scripts loaded:
10:59:08     |  * ia   buffers.pl 5.1 (Sidebar with list of buffers)
10:59:08     |    ia   highmon.pl 2.5 (Highlight Monitor)
10:59:08     |  * ia   iset.pl 3.9 (Interactive Set for configuration options)
10:59:08     |    ia   autojoin.py 0.2.5 (Configure autojoin for all servers according to currently joined channels)
10:59:08     |    ia   autosort.py 2.5 (Automatically or manually keep your buffers sorted and grouped by server.)
10:59:08     |    ia   colorize_nicks.py 21 (Use the weechat nick colors in the chat area)
10:59:08     |    ia   prism.py 0.2.8 (Taste the rainbow.)
10:59:08     |  * ia   urlserver.py 1.9 (Shorten URLs with own HTTP server)
10:59:08     |    ia   weestats.py 0.2 (Useless statistics about your open buffers and windows)
```

```
WeeChat 1.4-dev [compiled on Sep 17 2015 06:10:06]
Upgraded 1 time, first start: Wed, 21 Oct 2015 23:07:37
```

```
Message filtering enabled
No message filter defined
```

```
Triggers enabled
List of triggers:
  beep: print =? /1
  cmd_pass: modifier(5000|input_text_display;5000|history_add;5000|irc_command_auth) ~1
  msg_auth: modifier(5000|irc_message_auth) ~1
  server_pass: modifier(5000|input_text_display;5000|history_add) ~1
```

**Comment by flashcode** [comment]
Hi,
What is the OS used (and its version)?
And how much memory WeeChat is using? (RES column in command `top`)
You probably reached the max memory available, which causes such message in WeeChat.

**Comment by kashike** [comment]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
```

Current memory: `109M`
At the time this was happening, it was at around `509`.

**Comment by flashcode** [comment]
Lot of memory used are often caused by memory leaks in scripts, you can try to unload scripts (all or some of them), to test and find the guilty one.
WeeChat itself should never use 500MB (except if you are on thousands of channels with huge history in each channel...)

**Comment by kashike** [comment]
hrm, I've hit this issue again:
```
01:38:42 =!= | irc: reading data on socket: error -54 Error in the pull function.
01:38:42  -- | irc: disconnecting from server...
01:38:42  -- | irc: disconnected from server
01:38:42  -- | irc: reconnecting to server in 10 seconds
01:38:52  -- | irc: reconnecting to server...   
01:38:52  -- | irc: connecting to server irc.freenode.net/6697 (SSL)...
```

**Comment by kashike** [comment]
I've encountered this again many times, last night for example: https://gist.github.com/kashike/dc919aeedd4917e109ec#gistcomment-1733072
12:33:12 | WeeChat 1.5-dev (git: v1.4-102-g0be8e08) [compiled on Mar 10 2016 00:17:20]

**Comment by weechatter** [comment]
First of all you should upgrade nearly all scripts. Only two are currently up-to-date. Maybe this solve the problem. If not, remove all scripts. From my point of view i have buffers.pl, iset.pl and colorize_nicks.py running, without the problems you describe. i would guess that autojoin or autosort is the cuprit

**Comment by kashike** [comment]
This has been happening for a long time now - I've tried various things, including:
- removing all scripts except buffers.pl
- re-installing weechat
- not using relay (someone suggested it might be relay related)

**Comment by flashcode** [comment]
How much memory is using WeeChat (column RSS in ps or RES in top)?
And how much RAM do you have?

**Comment by kashike** [comment]
Currently, the `RES` column has a value of `95280`, while `VIRT` has `293M`. There's ~750M left for it to use.
~20 hours ago: `RES`: `74064`, `VIRT`: `259M`

**Comment by flashcode** [comment]
I fixed recently (some days ago) a "memory leak" (lot of memory used) in script API.
Maybe you could try the devel version and check if it's better? (be careful, it can be unstable due to major changes made for this fix)

**Comment by kashike** [comment]
I'll try a development build as soon as I have enough time - thanks for the information. Will keep this issue updated.

**Comment by matthiasbeyer** [comment]
I experience the same issue RSS from `ps aux` says 23848.

I used weechat 1.1.1 - I will now start a newer version and hope this issue vanishes.

**Comment by freijon** [comment]
I have the same issue. Just built a dev version from git, same issue. I got disconnected and can't reconnect. Even after a reboot.

**Comment by flashcode** [comment]
I will add some extra info in the errors displayed by the irc plugin. I hope this will help to fix the problem (if there's a bug in irc plugin, which is not sure).
I will ping you to test the devel version when this will be committed.

**Comment by flashcode** [comment]
I committed some extra info in the error messages, please try to compile and test the latest git version, and tell me the error message displayed in case of problem.

**Comment by flashcode** [comment]
Not sure, but this problem may be related to #358.

**Comment by kashike** [comment]
Hi @flashcode:

I'm getting the following error when trying to open an xfer:
```
02:50:30 =!= | xfer: not enough memory (fork)
02:50:30 =!= | xfer: error: fork
```

Environment:
weechat: `WeeChat 1.6-dev (git: v1.5-84-gb1d32b2)`
RES: `443M`
VIRT: `651M`
Overall usage: `662/992MB`

As usual, re-opening weechat (aftering exiting) "fixes" the issue.

**Comment by kashike** [comment]
I've updated to `WeeChat 1.6-dev (git: v1.5-103-g290b40a)` and I've given my VPS a restart, will see what happens.

**Comment by BohrShaw** [comment]
I just get the same error on Weechat running on Windows Sub-system for Linux.

**Comment by flashcode** [comment]
@BohrShaw: yes, fixed by #770 (currently only in devel version, the fix will be in version 1.6).

**Comment by flashcode** [comment]
@kashike: any news about this problem?

**Comment by kashike** [comment]
@flashcode: I've had this issue (irc: not enough memory) pop up a couple times, current running `WeeChat 1.7-dev (git: v1.6-41-g2122cbf) [compiled on Nov 15 2016 01:23:04]`. Exiting weechat and re-launching it is what I'm used to doing now.

I'll be moving my weechat installation to a new VPS in a couple of days, so perhaps when that's done this might be fixed.. somehow.

**Comment by kashike** [comment]
@flashcode seems to still be happening, currently with xfer - most likely with irc as well, I just haven't had to reconnect recently (no netsplits, etc)
```
16:00:12 =!= | xfer: not enough memory (fork)
16:00:12 =!= | xfer: error: fork
```

**Comment by flashcode** [comment]
Not enough memory for the fork seems to be a real memory issue.
What's the OS used, memory available and memory used by WeeChat?

**Comment by kashike** [comment]
```
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

`linux 4.8.13-1`

total used/available: `197M/1.95G`
weechat:
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
21090 kashike    20   0  307M  119M 19768 S  0.0  6.0  4:40.58 weechat --upgrade
```

**Comment by flashcode** [comment]
Then maybe for another reason weechat can not fork any more.
I'll add the fork error reason in the error message, and I'll ask you to test again (with git version) when done.

**Comment by kashike** [comment]
You probably won't get a response for a while - anywhere from a few days to a few weeks, depending on when it chooses to complain about memory, but I will test.

**Comment by flashcode** [comment]
Done, I added more info on fork errors.

**Comment by lol768** [comment]
I occassionally get this (v1.5), I always assumed it was due to the buffer content (NB: /close doesn't seem to fix the issue) but it could equally be a script.

Would running it with valgrind help?

**Comment by bendem** [comment]
I often get this (about once every week or two, using `WeeChat 1.6 [compiled on Oct  2 2016 13:24:49]`). When I start weechat, it uses around 15% of my RAM, as the days go by, it increases, until it gets killed at some point (or it kills every other process until it finally gets killed).

```
Scripts loaded:
* ia   buffers.pl 5.4 (Sidebar with list of buffers)
* ia   iset.pl 4.2 (Interactive Set for configuration options)
  ia   autosort.py 2.8 (Automatically or manually keep your buffers sorted and grouped by server.)
  ia   screen_away.py 0.14 (Set away status on screen detach)
```

```
Plugins loaded:
  trigger: Text replacement and command execution on events triggered by WeeChat/plugins
  alias: Alias commands
  perl: Support of perl scripts
  irc: IRC (Internet Relay Chat) protocol
  python: Support of python scripts
  script: Scripts manager
  logger: Log buffers to files
  relay: Relay WeeChat data to remote application (irc/weechat protocols)
  charset: Charset conversions
  exec: Execution of external commands in WeeChat
```

```
$ uname -a
Linux bendem 2.6.32-042stab116.1 #1 SMP Wed May 4 16:21:02 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by tpruzina** [comment]
Perhaps you could analyze the leak via valgrind (+massif) and post results here (inducing core dump would be nice as well but I uploading a dump would would leak all your credentials I presume).
It shouldn't be that hard to roughly localize source of the leak from valgrind log.

**Comment by lol768** [comment]
Valgrind in memcheck tool mode: https://gist.github.com/anonymous/8faea941b1c67f7d45a1cf179a4bc3bf
I haven't tried using `--tool=massif` yet but hopefully this is a start.

Not sure it tells us much, though maybe the python stuff is an indicator there's a script issue? I can try doing a binary chop on the enabled scripts.

Core dump I'll avoid doing unless I can reproduce connecting to an unimportant test server.

NB: weechat becomes very unusable when run under valgrind IME, the above log is based on a few hours usage, not enough usage to make the system run out of memory. Hopefully it's still useful.

**Comment by weechatter** [comment]
@lol768 : beside the memory issue, I don't know your weechat version but you should replace some of your scripts, because they are obsolete:

toogle_nicklist.py -> use a trigger or better a bar condition
shell.py -> use the core command /exec

and the "N" right hand of the script name means, there is a newer version from script. Therefore run
/script upgrade

**Comment by tpruzina** [comment]
@lol768 ```15,837 bytes in 92 blocks``` it's only 15kB, can you try to run it with valgrind in such a manner that memleak will propagate?

**Comment by tpruzina** [comment]
@lol768 Unfortunatedly there isn't too much that valgrind is showing in leacheck mode (only 15kB leak), massif mode actually tracks "legitimate" allocations and where in code they occur.

**Comment by lol768** [comment]
@tpruzina yeah, figured as much.. I'll compile latest weechat, update everything and give that a go.

Cheers.

**Comment by Roliga** [comment]
I've been experiencing this issue too so I ran weechat through valgrind with the massif tool over night, connecting to a [weercd](https://github.com/weechat/weercd) instance. I'm not sure how useful this will be, but here's the [ms_print output](https://gist.github.com/Roliga/5aebb1770ce650ed2f721bf0ffb18f73) and [these](https://gist.github.com/Roliga/37f9575ae34c0e54f48d8860d2c947e0) are the scripts that I had loaded.

I also tried closing all buffers and unloading all scripts and plugins, and while that released some memory, a lot was still allocated.

**Comment by kashike** [comment]
I've been restarting weechat almost weekly now, so I've started connecting through ZNC to stop myself from joining/quitting all the time.

Currently: `WeeChat 1.8-dev (git: v1.7-5-g2f2b04e13) [compiled on Jan 18 2017 16:25:16]`

**Comment by weechatter** [comment]
@kashike: your system?
And how much memory WeeChat is using? (RES column in command top)
/script list

I can only say i am running WeeChat on an raspberry Pi:
WeeChat-Laufzeit: 71 Tage 18:42:12, gestartet am Di, 15 Nov 2016 21:47:46

**Comment by kashike** [comment]
Currently, connecting through ZNC:
`WeeChat 1.8-dev (git: v1.7-5-g2f2b04e13) [compiled on Jan 18 2017 16:25:16]`
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
 6622 kashike    20   0  277M 91540 19676 S  2.0  4.5  4:35.53 weechat
```

```
16:38:16 | Scripts loaded:
16:38:16 |  * ia   buffers.pl 5.4 (Sidebar with list of buffers)
16:38:16 |    ia   color_popup.pl 0.4 (show mirc color codes)
16:38:16 |  * ia   iset.pl 4.2 (Interactive Set for configuration options)
16:38:16 |    ia   autojoin.py 0.2.6 (Configure autojoin for all servers according to currently joined channels)
16:38:16 |    ia   autosort.py 2.8 (Automatically or manually keep your buffers sorted and grouped by server.)
16:38:16 |    ia   weestats.py 0.3 (Useless statistics about your open buffers and windows)
16:38:16 |    ia   whois_on_query.py 0.6 (Whois on query)
```

**Comment by kashike** [comment]
`WeeChat 1.8-dev (git: v1.7-52-gf4c2328ab) [compiled on Feb 23 2017 15:21:32]`

Usage:
![x](http://i.imgur.com/EqOPwKU.png)

Just upgraded:
```
WeeChat 1.8-dev (git: v1.7-64-geebb0547e) [compiled on Mar 20 2017 21:39:08]
Upgraded 1 time, first start: Sat, 04 Mar 2017 14:12:22, last start: Mon, 20 Mar 2017 21:40:37
```


```
21:42 Scripts loaded:
21:42  * ia   buffers.pl 5.6 (Sidebar with list of buffers)
21:42    ia   color_popup.pl 0.4 (show mirc color codes)
21:42  * ia   iset.pl 4.2 (Interactive Set for configuration options)
21:42    ia   autojoin.py 0.2.6 (Configure autojoin for all servers according to currently joined channels)
21:42    ia   autosort.py 2.8 (Automatically or manually keep your buffers sorted and grouped by server.)
21:42    ia   prism.py 0.2.10 (Taste the rainbow.)
21:42    ia   weestats.py 0.3 (Useless statistics about your open buffers and windows)
21:42    ia   whois_on_query.py 0.6 (Whois on query)
```

**Comment by afics** [comment]
`WeeChat 1.7 [compiled on Jan 18 2017 17:48:07]`

I am affected by this as well, currently weechat is using about 5G of RAM.

```
10:27:59 	<>	Scripts loaded:
10:27:59 	<>	 * iaHN buffers.pl 5.1 (Sidebar with list of buffers)
10:27:59 	<>	   ia   highmon.pl 2.5 (Highlight Monitor)
10:27:59 	<>	 * ia   iset.pl 4.2 (Interactive Set for configuration options)
10:27:59 	<>	   ia   listsort.pl 0.1 (Sort the output of /list command by user count)
10:27:59 	<>	   ia   mass_hl_blocker.pl 0.1 (Block mass highlights)
10:27:59 	<>	   ia   nickregain.pl 1.1.1 (Auto Nick Regaining)
10:27:59 	<>	   ia   recoverop.pl 0.1.1 (recover channel operator in empty channel)
10:27:59 	<>	   ia   autojoin.py 0.2.6 (Configure autojoin for all servers according to currently joined channels)
10:27:59 	<>	   ia   autosavekey.py 0.3 (save channel key from protected channel(s) to autojoin or secure data)
10:27:59 	<>	   ia   autosort.py 2.8 (Automatically or manually keep your buffers sorted and grouped by server.)
10:27:59 	<>	   ia   chancomp.py 1.1 (List shared channels with user on command or WHOIS)
10:27:59 	<>	   ia   chanstat.py 0.1 (Channel statistics)
10:27:59 	<>	   ia   colorize_nicks.py 23 (Use the weechat nick colors in the chat area)
10:27:59 	<>	   ia   confversion.py 0.2 (Stores version controlled history of your configuration files)
10:27:59 	<>	   ia   country.py 0.6 (Prints user's country and local time in whois replies)
10:27:59 	<>	   ia   go.py 2.5 (Quick jump to buffers)
10:27:59 	<>	   ia   keepnick.py 1.3 (keep your nick and recover it in case it's occupied)
10:27:59 	<>	   ia   listbuffer.py 0.8.1 (A common buffer for /list output.)
10:27:59 	<>	   ia   logsize.py 0.3 (display size of current logfile in item-bar)
10:27:59 	<>	   ia   maskmatch.py 1.4 (Display who got banned (quieted, excepted, etc.) when a mode with a hostmask argument is set)
10:27:59 	<>	   ia   otr.py 1.8.0 (Off-the-Record messaging for IRC)
10:27:59 	<>	   ia   postpone.py 0.2.3 (Postpones written messages for later dispatching if target nick is not on channel)
10:27:59 	<>	   ia   queryman.py 0.3 (save and restore query buffers after /quit)
10:27:59 	<>	   ia   title.py 0.8 (Set screen title to current buffer name + hotlist items with configurable priority level)
10:27:59 	<>	   ia   topicdiff.py 0.3 (Show differences between old and new topics.)
10:27:59 	<>	   ia   weestats.py 0.3 (Useless statistics about your open buffers and windows)
10:27:59 	<>	   ia   whois_on_query.py 0.6 (Whois on query)
10:27:59 	<>	   ia   whowas_timeago.py 1.2 (Display a human-readable time string for WHOWAS data)
10:27:59 	<>	   ia   zerotab.py 1.5 (Will tab complete the last nick in channel without typing anything first. This is good for rapid conversations.)
10:27:59 	<>	   ia   url_hinter.rb 0.2 (Open an url in the weechat buffer to type a hint)
```

**Comment by Roliga** [comment]
@afics: Look into updating your buffers.pl script. Some memory leak issues were fixed in it recently, version 5.5 as far as I can remember. It helped a lot for me at least.

**Comment by afics** [comment]
@Roliga Thanks, I'll try that.

**Comment by bendem** [comment]
Just letting you know, after the update to 1.8 and replacing buffers.pl with the buflist plugin. I don't have memory problems anymore.

**Comment by lol768** [comment]
+1 @bendem 

Dumping `buffers.pl` for the 1.8 buflist also fixed my memory issues.

**Comment by weechatter** [comment]
There is a known memory leak problem with some perl versions and buffers.pl. a work-around was provided with buffers.pl 5.5:
fix memory leak in perl 5.23.7-5.24.1
But i suggest using new buflist-plugin anyway and to /script remove buffers.pl

**Comment by bendem** [comment]
Yeah, I tried latest buffers.pl, if it got better, it wasn't noticeable.

**Comment by lol768** [comment]
@weechatter said:
>There is a known memory leak problem with some perl versions and buffers.pl. a work-around was provided with buffers.pl 5.5:

@lol768 said:
> I was on the latest version of the script and still hitting issues, fwiw.

Perhaps the update improved things, but it still wasn't ideal.

**Comment by kashike** [comment]
As far as I can tell this has been resolved by using `buflist` instead of `buffers.pl`.

:dancer:
