### ISSUE TITLE
segfault while loading multiple perl scripts from perl

### ISSUE THREAD

**Issue by voldenet** [weechat/weechat#923]
**load.pl:**
```
weechat::register "load", "v", "0.1", "GPL3", "", "", "";       
weechat::command "", "/perl load no.pl";                        
weechat::command "", "/perl load no2.pl";
```

**no.pl**
`weechat::register "no", "v", "0.1", "GPL3", "", "", "";`

**no2.pl**
`weechat::register "no", "v", "0.1", "GPL3", "", "", "";`

When running /perl load load.pl I'm receiving a SIGSEGV with the following backtrace:
```
======= WeeChat backtrace =======
(written by WeeChat 1.7, compiled on Jan 15 2017 09:58:52)
001  ??:? [function weechat_backtrace]
002  ??:? [function debug_sigsegv]
003  ??:? [function __restore_rt]
addr2line: '0x352a1': No such file
addr2line: '0xcd81b': No such file
addr2line: '0xc6056': No such file
addr2line: '0x4ef61': No such file
addr2line: '0x4f303': No such file
addr2line: '0x9486': No such file
addr2line: '0xbb10': No such file
011  ??:? [function hook_command_exec]
012  ??:? [function input_exec_command]
013  ??:? [function input_data]
014  ??:? [function gui_input_return]
015  ??:? [function command_input]
016  ??:? [function hook_command_exec]
017  ??:? [function input_exec_command]
018  ??:? [function input_data]
019  ??:? [function gui_key_pressed]
020  ??:? [function gui_key_flush]
021  ??:? [function gui_key_read_cb]
022  ??:? [function hook_fd_exec]
023  ??:? [function gui_main_loop]
024  ??:? [function main]
025  ??:? [function __libc_start_main]
026  ??:? [function _start]
======= End of  backtrace =======
```

**Comment by arza-zara** [comment]
Reproduced in archlinux and debian jessie with latest git:
```
weechat::register("crash", "no", "0.1", "GPL3", "", "", "");
weechat::command("", "/script load something.pl");
weechat::command("", "/print test");
```
```
Program terminated with signal SIGABRT, Aborted.
#0  0xf72fde2c in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#0  0xf72fde2c in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = <optimized out>
        resultvar = <optimized out>
        pid = -146538496
        selftid = 14388
#1  0xf72ff4b3 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x5, sa_sigaction = 0x5}, sa_mask = {__val = {0, 4148428800, 172520632, 4151992320, 4151994672, 5, 171735920, 4151917663, 4151995112, 4142857104, 1, 5, 0, 4151078912, 0, 166201896, 171735892, 135516184, 134568360, 134531704, 0, 4149989162, 4130971648, 4146946324, 4130580264, 134809379, 166524216, 4130971648, 3708818532, 4130580264, 3708818528, 4151943136}}, sa_flags = 1, sa_restorer = 0xf72ff370 <__GI_abort>}
        sigs = {__val = {32, 0 <repeats 31 times>}}
#2  0x080656d8 in weechat_shutdown ()
#3  0x080817d8 in debug_sigsegv ()
#4  <signal handler called>
#5  0xf637261b in XS_weechat_api_command () from /usr/lib/weechat/plugins/perl.so
#6  0xf620902c in Perl_pp_entersub () from /usr/lib/i386-linux-gnu/libperl.so.5.20
#7  0xf6201747 in Perl_runops_standard () from /usr/lib/i386-linux-gnu/libperl.so.5.20
#8  0xf6189395 in Perl_eval_sv () from /usr/lib/i386-linux-gnu/libperl.so.5.20
#9  0xf61896c0 in Perl_eval_pv () from /usr/lib/i386-linux-gnu/libperl.so.5.20
#10 0xf6341e02 in weechat_perl_load () from /usr/lib/weechat/plugins/perl.so
#11 0xf634487f in weechat_perl_command_cb () from /usr/lib/weechat/plugins/perl.so
#12 0x08088058 in hook_command_exec ()
#13 0x0808ee1d in input_exec_command ()
#14 0x0808f263 in input_data ()
#15 0x080d7759 in plugin_api_command ()
#16 0xf609eab7 in script_action_load () from /usr/lib/weechat/plugins/script.so
#17 0xf60a02a3 in script_action_run () from /usr/lib/weechat/plugins/script.so
#18 0xf60a0aa9 in script_action_schedule () from /usr/lib/weechat/plugins/script.so
#19 0xf60a3445 in script_command_action () from /usr/lib/weechat/plugins/script.so
#20 0xf60a3788 in script_command_script () from /usr/lib/weechat/plugins/script.so
#21 0x08088058 in hook_command_exec ()
#22 0x0808ee1d in input_exec_command ()
#23 0x0808f263 in input_data ()
#24 0x080b8990 in gui_input_return ()
#25 0x08069559 in command_input ()
#26 0x08088058 in hook_command_exec ()
#27 0x0808ee1d in input_exec_command ()
#28 0x0808f263 in input_data ()
#29 0x080bc364 in gui_key_pressed ()
#30 0x080ce1ea in gui_key_flush ()
#31 0x080ce63c in gui_key_read_cb ()
#32 0x080887d9 in hook_fd_exec ()
#33 0x080cf0a0 in gui_main_loop ()
#34 0x080650f5 in main ()
```

**Comment by flashcode** [comment]
Hi,
I can not reproduce the crash with the latest version (4.0.4 or 4.1.0-dev), it could have been fixed in the meanwhile.
Could you please confirm?

**Comment by trygveaa** [comment]
This still reproduces for me on Arch Linux with current master (commit 2092715ac).

Here's a backtrace for that version with line numbers:

```
(written by WeeChat 4.1.0-dev (git: v4.0.0-164-g2092715ac), compiled on Aug 24 2023 20:52:31)
001  /home/trygve/dev/weechat/src/core/wee-backtrace.c:167 [function weechat_backtrace]
002  /home/trygve/dev/weechat/src/core/wee-debug.c:187 [function debug_sigsegv_cb]
003  ??:? [function rb_bug_reporter_add]
004  ??:? [function ruby_sysinit]
005  ??:? [function __sigaction]
006  /home/trygve/dev/weechat/src/plugins/perl/weechat-perl-api.c:4387 (discriminator 2) [function XS_weechat_api_command]
007  :? [function Perl_pp_entersub]
008  ??:? [function Perl_runops_standard]
009  ??:? [function Perl_eval_sv]
010  ??:? [function Perl_eval_pv]
011  /home/trygve/dev/weechat/src/plugins/perl/weechat-perl.c:604 [function weechat_perl_load]
012  /home/trygve/dev/weechat/src/plugins/perl/weechat-perl.c:969 [function weechat_perl_command_cb]
013  /home/trygve/dev/weechat/src/core/hook/wee-hook-command.c:504 [function hook_command_exec]
014  /home/trygve/dev/weechat/src/core/wee-input.c:161 (discriminator 1) [function input_exec_command]
015  /home/trygve/dev/weechat/src/core/wee-input.c:335 [function input_data]
016  /home/trygve/dev/weechat/src/core/wee-command.c:9348 [function command_exec_list]
017  /home/trygve/dev/weechat/src/core/wee-command.c:9369 (discriminator 3) [function command_startup]
018  /home/trygve/dev/weechat/src/core/weechat.c:686 [function weechat_init]
019  /home/trygve/dev/weechat/src/gui/curses/normal/main.c:44 [function main]
020  ??:? [function __libc_init_first]
021  ??:? [function __libc_start_main]
022  ??:? [function _start]
```

Attached is the log from asan: [asan.log](https://github.com/weechat/weechat/files/12437182/asan.log)

**Comment by flashcode** [comment]
Right, I can also reproduce now, when compiled with the Address Sanitizer as well.

I think loading a script inside the script init is just not supported, I'll check how to fix this.

**Comment by flashcode** [comment]
Interesting, in fact it crashes with `/script load crash.pl` but not with `/perl load crash.pl` (with the same script being executed).

**Comment by trygveaa** [comment]
> Interesting, in fact it crashes with `/script load crash.pl` but not with `/perl load crash.pl` (with the same script being executed).

Hm, for me it crashes with both.

**Comment by flashcode** [comment]
@trygveaa: and what's the content of your test script?

**Comment by flashcode** [comment]
I found an issue in the script plugin when a `/script` command is executed inside another one, this patch should fix it, could you please test?

```diff
diff --git a/src/plugins/script/script-action.c b/src/plugins/script/script-action.c
index eae0e63d3..7de928e3a 100644
--- a/src/plugins/script/script-action.c
+++ b/src/plugins/script/script-action.c
@@ -1300,6 +1300,9 @@ script_action_run_all ()
                                     | WEECHAT_STRING_SPLIT_STRIP_RIGHT
                                     | WEECHAT_STRING_SPLIT_COLLAPSE_SEPS,
                                     0, &num_actions);
+
+    script_action_clear ();
+
     if (actions)
     {
         for (i = 0; i < num_actions; i++)
@@ -1564,8 +1567,6 @@ script_action_run_all ()
         weechat_string_free_split (actions);
     }
 
-    script_action_clear ();
-
     return 1;
 }

```

**Comment by trygveaa** [comment]
> @trygveaa: and what's the content of your test script?

I used exactly the scripts posted in the first message here. I see that the crash only occurs if an error happens. In this case it apparently errors because the `load.pl` script runs `/perl load no.pl` rather than `/perl load ./no.pl`

> I found an issue in the script plugin when a /script command is executed inside another one, this patch should fix it, could you please test?

This doesn't seem to change anything for me.

It looks like the problem is that when it errors on loading `no.pl` it frees `perl_current_interpreter` on `src/plugins/perl/weechat-perl.c:640`. And then on `src/plugins/perl/weechat-perl-api.c:4387` when it is going to return from running the command that errored it crashes because the interpreter has been freed.

So if you only free the interpreter if there's only one script loading, that fixes the crash. But I assume this code wasn't written with multiple loads happening at the same time in mind, since `perl_current_interpreter` is a global variable that is overwritten for each load. So not sure if it causes problems that the nested load overwrites the parent one.

Also, `perl_current_interpreter` is allocated each time a perl script is loaded, but only freed if an error occurs. Won't that cause memory leaks?

I also get another weird error (not crash) if I change `load.pl` to use `/perl load ./no.pl` and `/perl load ./no2.pl`. It then loads `no.pl` fine, but when running `/perl load ./no2.pl` it gives the error:

```
perl: wrong arguments for function "command" (script: no)
```

This doesn't make sense since the arguments for the command is correct. So I guess some issue occurs since multiple scripts are loading at the same time.

**Comment by flashcode** [comment]
> > I found an issue in the script plugin when a /script command is executed inside another one, this patch should fix it, could you please test?
> 
> This doesn't seem to change anything for me.

Weird, but since I have a crash, I'll fix this issue anyway.

> It looks like the problem is that when it errors on loading `no.pl` it frees `perl_current_interpreter` on `src/plugins/perl/weechat-perl.c:640`. And then on `src/plugins/perl/weechat-perl-api.c:4387` when it is going to return from running the command that errored it crashes because the interpreter has been freed.
> 
> So if you only free the interpreter if there's only one script loading, that fixes the crash. But I assume this code wasn't written with multiple loads happening at the same time in mind, since `perl_current_interpreter` is a global variable that is overwritten for each load. So not sure if it causes problems that the nested load overwrites the parent one.

I think the problem is not this variable by itself, because in function weechat_perl_exec, the Perl context is set at beginning and restored at the end.
But the problem is that the function weechat_perl_load actually changes the Perl context, and this can happen during execution of weechat_perl_exec.

I think the weechat_perl_load should do like weechat_perl_exec: restore the old interpreter at the end.

> 
> Also, `perl_current_interpreter` is allocated each time a perl script is loaded, but only freed if an error occurs. Won't that cause memory leaks?

This pointer is stored in the script structure and should be freed when the script is unloaded (weechat-perl.c:731).

> 
> I also get another weird error (not crash) if I change `load.pl` to use `/perl load ./no.pl` and `/perl load ./no2.pl`. It then loads `no.pl` fine, but when running `/perl load ./no2.pl` it gives the error:
> 
> ```
> perl: wrong arguments for function "command" (script: no)
> ```
> 
> This doesn't make sense since the arguments for the command is correct. So I guess some issue occurs since multiple scripts are loading at the same time.
